#   _______                       __        __    __
#  /       \                     /  |      /  |  /  |
#  $$$$$$$  |  ______   _______  $$ |   __ $$ |  $$ |  ______
#  $$ |__$$ | /      \ /       \ $$ |  /  |$$ |  $$ | /      \
#  $$    $$<  $$$$$$  |$$$$$$$  |$$ |_/$$/ $$ |  $$ |/$$$$$$  |
#  $$$$$$$  | /    $$ |$$ |  $$ |$$   $$<  $$ |  $$ |$$ |  $$ |
#  $$ |  $$ |/$$$$$$$ |$$ |  $$ |$$$$$$  \ $$ \__$$ |$$ |__$$ |
#  $$ |  $$ |$$    $$ |$$ |  $$ |$$ | $$  |$$    $$/ $$    $$/
#  $$/   $$/  $$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/  $$$$$$$/
#                                                    $$ |
#  The easy prison rankup plugin for PocketMine-MP   $$ |
#                                                    $$/

unleash-the-rankupdoesgroups: true
  # If you set this to false RankUpDoesGroups won't be loaded.
  # This means that you can't set it as your groupmanager.
  # It is highly recommended not to change this
preferred-economy: false
  # Set your preferred economy
  # rankup\\economy\\Economy and rankup\\economy\\PocketMoney are available by default
  # Set to false for autoloading (only officially supported economys will autoload).
preferred-groupmanager: "rankup\\permission\\RankUpDoesGroups"
  # Set your preferred group manager
  # rankup\\permission\\RankUpDoesGroups and rankup\\permission\\PurePerms are available.
  # RankUpDoesGroups is a super barebones alternative for users who don't use PurePerms

ranks: # Define all your ranks here
  A: 0
  B: 0
  C: 15
  D: 50

lang:
  ranked-up-paid: "You have been ranked up to %s"
  ranked-up-free: "You have been ranked up to %s"
  group-add-error-paid: "Failed to rankup. Refunded price."
  group-add-error-free: "Failed to rankup. Try again later."
  need-more-money-1: "Looks like you don't have enough money."
  need-more-money-2: "You need %s to rank up."
  missing-economy: "Can't purchase now."
  have-max-rank: "You have the maximum rank."
  command-permission-error: "You don't have permission to rankup."


